### ISSUE TITLE
Feature Request: Remove Individual Items from the List

### ISSUE THREAD

**Issue by vinaytheprogrammer** [myaxyo/youtube-filter-extension#1]
Hi,
Thank you for creating this amazing tool! It works really well and performs as intended.

However, I would like to suggest an improvement. Currently, the only way to remove items from the list is to reset the entire list, which can be inconvenient if I want to remove just one or two items.

**Feature Request:**
Please consider adding a feature to allow users to remove specific items from the list without resetting the entire list. This would make the tool more user-friendly and efficient.

**Benefits:**

Better control over list management
Enhanced user experience
Reduces repetitive tasks

![image](https://github.com/user-attachments/assets/66bd731b-a8b1-4708-aea0-07da8764ba67)

**Comment by myaxyo** [comment]
Hey! I am really excited as you are interested my small project.

Please can you try click on individual keywords to remove one? Please let me know if it works.

**Comment by vinaytheprogrammer** [comment]
i already solved this, I'll be sending you a PR, please allot this issue to me.

**Comment by vinaytheprogrammer** [comment]
I'd be happy to provide more details about the [feature/bug] I'm experiencing. Please let me know if you'd like me to elaborate in a separate communication channel. please contact me vinaygupta.nitjsr@gmail.com
